// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjuadqspluysbimyqgjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqdWFkcXNwbHV5c2JpbXlxZ2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDg0NDksImV4cCI6MjA2NTgyNDQ0OX0.rH8JTWc2bjtnwJQenFp767uDWG39VExvf8L_mPOZVyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);